"""Settings — thin wrapper around config.py for backward compatibility."""

from .config import (
    MODE, ADMIN_TOKEN, CORS_ORIGINS, PAPER_CAPITAL, DB_PATH,
    API_HOST, API_PORT, WEB_PORT,
    MAX_ORDER_NOTIONAL, MAX_TOTAL_EXPOSURE,
    DEFAULT_FEE_BPS, DEFAULT_SLIPPAGE_BPS, DEFAULT_CHUNKS, DEFAULT_DELAY_MS,
    HTTP_TIMEOUT, AI_TIMEOUT,
    OPENCODE_API_KEY, OPENCODE_MODEL, OPENCODE_BASE_URL,
    OPENROUTER_API_KEY, OPENROUTER_MODEL, OPENROUTER_BASE_URL,
    BINANCE_SPOT_URL, BINANCE_FUTURES_URL,
    BINANCE_TESTNET_SPOT_URL, BINANCE_TESTNET_FUTURES_URL,
    SYMBOLS,
)

# Alias for existing imports
API_ORIGINS = CORS_ORIGINS
